import type { ProviderAdapter } from "../providers/interface.js";

// ============================================================
// OWASP LLM Top 10 Categories + KindLM-specific additions
// ============================================================

/**
 * Attack categories used by built-in red team plugins.
 *
 * `LLM01`..`LLM10` mirror the OWASP LLM Top 10 (2025). Not every LLM category
 * has a built-in plugin yet — `LLM03`, `LLM04`, and `LLM08` are reserved for
 * future slices. `HARMFUL_CONTENT` and `CUSTOM_POLICY` are KindLM-specific.
 */
export type RedTeamCategory =
  | "LLM01" // Prompt Injection
  | "LLM02" // Sensitive Information Disclosure
  | "LLM03" // Supply Chain (reserved)
  | "LLM04" // Data and Model Poisoning (reserved)
  | "LLM05" // Improper Output Handling
  | "LLM06" // Excessive Agency
  | "LLM07" // System Prompt Leakage
  | "LLM08" // Vector and Embedding Weaknesses (reserved)
  | "LLM09" // Misinformation
  | "LLM10" // Unbounded Consumption
  | "HARMFUL_CONTENT"
  | "CUSTOM_POLICY";

// ============================================================
// Severity
// ============================================================

export type Severity = "critical" | "high" | "medium" | "low";

export const SEVERITIES: readonly Severity[] = [
  "critical",
  "high",
  "medium",
  "low",
] as const;

// ============================================================
// Attack & Verdict Shapes
// ============================================================

/**
 * A single red team attack probe generated by a plugin.
 *
 * Plugins generate attacks ahead of time; the engine then runs each one
 * against the target model and passes the resulting output back to
 * `grade()` for evaluation.
 */
export interface Attack {
  /** Plugin id that produced this attack (e.g. "prompt-injection"). */
  pluginId: string;
  /** OWASP / KindLM category this attack belongs to. */
  category: RedTeamCategory;
  /** Effective severity for this probe (plugin default or user override). */
  severity: Severity;
  /** Short human-readable label for this specific probe. */
  label: string;
  /** The user-turn prompt the target model will see. */
  userPrompt: string;
  /** Optional system prompt override; falls back to `target.prompt` when unset. */
  systemPrompt?: string;
  /** Free-form metadata the plugin may use when grading the response. */
  metadata?: Record<string, unknown>;
}

/**
 * Result of grading a target model's response to an {@link Attack}.
 */
export interface AttackVerdict {
  /** The attack that was graded. */
  attack: Attack;
  /** True when the target model successfully resisted the attack. */
  passed: boolean;
  /** 0..1 score — higher means stronger resistance. */
  score: number;
  /** Short reason string suitable for reports. */
  reason: string;
  /** Optional structured detail for downstream reporters. */
  details?: Record<string, unknown>;
}

// ============================================================
// Plugin Runtime Context
// ============================================================

/**
 * Runtime context passed to plugin `generate` and `grade` methods.
 *
 * Core remains zero-I/O — all provider calls flow through injected
 * {@link ProviderAdapter}s so the red team engine stays testable.
 */
export interface RedTeamPluginContext {
  /** The application's stated purpose — used to craft targeted attacks. */
  purpose: string;
  /** Model id of the target being probed. */
  targetModel: string;
  /** Optional base system prompt used by the target in production. */
  targetPrompt?: string;
  /** Adapter used to call the target model. */
  targetAdapter: ProviderAdapter;
  /** Optional adapter for LLM-as-judge graders. */
  judgeAdapter?: ProviderAdapter;
  /** Optional judge model id. */
  judgeModel?: string;
  /** When true, enable the beta multi-judge/ensemble path. */
  betaJudge?: boolean;
  /** Plugin-specific config block from the YAML. */
  pluginConfig?: Record<string, unknown>;
  /** Number of probes this plugin should generate. */
  numTests: number;
  /** Effective severity (plugin default or user override). */
  severity: Severity;
}
