import * as core from '@actions/core';
import * as github from '@actions/github';
import type { KindlmJsonReport } from './types.js';

const MARKER = '<!-- kindlm-test-results -->';

/**
 * Build the PR comment body in the D-16 markdown format.
 * ACTION-08/D-18: Only uses test.name, test.status, assertion.label, assertion.failureMessage.
 * Never includes any field that could contain raw model response text.
 */
export function buildCommentBody(
  report: KindlmJsonReport,
  passRate: number,
  cloudUrl?: string,
): string {
  const { totalTests, passed, failed } = report.summary;

  const table = [
    `| Status | Count |`,
    `|--------|-------|`,
    `| Passed | ${passed} |`,
    `| Failed | ${failed} |`,
    `| Total | ${totalTests} |`,
  ].join('\n');

  const lines: string[] = [
    MARKER,
    `## KindLM Test Results`,
    ``,
    table,
    ``,
    `**Pass rate:** ${passRate.toFixed(1)}%`,
  ];

  // Collect failing tests — only use safe fields (name, label, failureMessage)
  const failingTests: Array<{ suite: string; test: string; reason: string }> = [];
  for (const suite of report.suites) {
    for (const test of suite.tests) {
      if (test.status !== 'passed') {
        const firstFailed = test.assertions.find((a) => !a.passed);
        const reason = firstFailed?.failureMessage ?? firstFailed?.label ?? 'assertion failed';
        failingTests.push({ suite: suite.name, test: test.name, reason });
      }
    }
  }

  if (failingTests.length > 0) {
    lines.push(``, `### Failing Tests`);
    for (const { suite, test, reason } of failingTests) {
      lines.push(`- \`${suite}/${test}\`: ${reason}`);
    }
  }

  const reportLink = cloudUrl ? ` | [Report](${cloudUrl})` : '';
  lines.push(``, `<sub>Generated by [KindLM](https://kindlm.com)${reportLink}</sub>`);

  return lines.join('\n');
}

/**
 * Post or update a PR comment using the hidden marker for dedup (D-17).
 * Guards on eventName, GITHUB_TOKEN presence, and PR number availability.
 * Wraps all Octokit calls in try/catch — 403 on fork PRs is non-fatal (Pitfall 1).
 */
export async function upsertPrComment(body: string): Promise<void> {
  // Pitfall 7: only runs on pull_request events
  if (github.context.eventName !== 'pull_request') return;

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    core.warning('GITHUB_TOKEN not set, skipping PR comment');
    return;
  }

  const prNumber = github.context.payload.pull_request?.number;
  if (!prNumber) return;

  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const comments = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100,
    });

    const existing = comments.data.find((c) => c.body?.includes(MARKER));

    if (existing) {
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existing.id,
        body,
      });
    } else {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body,
      });
    }
  } catch (err) {
    // Pitfall 1: fork PRs return 403 — log warning, never throw
    core.warning(`PR comment failed (non-fatal): ${err}`);
  }
}
