// @ts-expect-error pdfkit has no type declarations
import PDFDocument from "pdfkit";
import { createWriteStream } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

interface Section {
  heading: string;
  headingLevel: number;
  body: string;
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split("\n");
  const sections: Section[] = [];
  let currentHeading = "";
  let currentLevel = 2;
  let currentBody: string[] = [];

  for (const line of lines) {
    const headingMatch = line.match(/^(#{2,4})\s+(.+)$/);
    if (headingMatch && headingMatch[1]?.length === 2) {
      if (currentHeading || currentBody.length > 0) {
        sections.push({ heading: currentHeading, headingLevel: currentLevel, body: currentBody.join("\n").trim() });
      }
      currentHeading = headingMatch[2]?.trim() ?? "";
      currentLevel = 2;
      currentBody = [];
    } else {
      currentBody.push(line);
    }
  }

  if (currentHeading || currentBody.length > 0) {
    sections.push({ heading: currentHeading, headingLevel: currentLevel, body: currentBody.join("\n").trim() });
  }

  return sections;
}

function extractTitle(markdown: string): string {
  const match = markdown.match(/^# (.+)$/m);
  return match?.[1]?.trim() ?? "KindLM Compliance Report";
}

function extractHash(markdown: string): string | null {
  const match = markdown.match(/SHA-256:\s*`([a-f0-9]+)`/i);
  return match?.[1] ?? null;
}

function headingSize(level: number): number {
  switch (level) {
    case 2: return 18;
    case 3: return 15;
    case 4: return 13;
    default: return 13;
  }
}

interface TableRow {
  cells: string[];
}

function parseTable(lines: string[]): { header: TableRow; rows: TableRow[] } | null {
  if (lines.length < 2) return null;
  const headerLine = lines[0] ?? "";
  const separatorLine = lines[1] ?? "";
  if (!headerLine.includes("|") || !separatorLine.match(/^\s*\|[-:\s|]+\|\s*$/)) return null;

  const parseCells = (line: string): string[] =>
    line.split("|").slice(1, -1).map((c) => c.trim());

  const header: TableRow = { cells: parseCells(headerLine) };
  const rows: TableRow[] = [];
  for (let i = 2; i < lines.length; i++) {
    const row = lines[i] ?? "";
    if (!row.includes("|")) break;
    rows.push({ cells: parseCells(row) });
  }
  return { header, rows };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type PDFDoc = any;

function ensureSpace(doc: PDFDoc, needed: number): void {
  const bottomMargin = doc.page.margins.bottom as number;
  const available = (doc.page.height as number) - bottomMargin - 30 - (doc.y as number);
  if (available < needed) {
    doc.addPage();
    renderPageHeader(doc);
  }
}

function renderPageHeader(doc: PDFDoc): void {
  const timestamp = new Date().toISOString();
  doc.fontSize(8).font("Helvetica").fillColor("#a8a29e").text("KindLM Compliance Report", 60, 40);
  doc.text(timestamp, 60, 40, { align: "right" });
  doc.moveDown(3);
}

function renderPageFooter(doc: PDFDoc): void {
  doc.fontSize(8).font("Helvetica").fillColor("#a8a29e").text(
    "Generated by KindLM · kindlm.com",
    60,
    (doc.page.height as number) - 50,
    { align: "center", width: (doc.page.width as number) - 120 },
  );
}

function renderTable(
  doc: PDFDoc,
  table: { header: TableRow; rows: TableRow[] },
  contentWidth: number,
): void {
  const colCount = table.header.cells.length;
  const colWidth = contentWidth / colCount;
  const leftMargin = doc.page.margins.left as number;
  const rowHeight = 18;

  ensureSpace(doc, rowHeight * 2);

  const drawRow = (cells: string[], bold: boolean, bgColor?: string) => {
    const y = doc.y as number;
    if (bgColor) {
      doc.save();
      doc.rect(leftMargin, y - 2, contentWidth, rowHeight).fill(bgColor);
      doc.restore();
    }
    for (let i = 0; i < cells.length; i++) {
      const x = leftMargin + i * colWidth;
      doc.fontSize(8)
        .font(bold ? "Helvetica-Bold" : "Courier")
        .fillColor("#44403c")
        .text(cells[i] ?? "", x + 4, y, { width: colWidth - 8, height: rowHeight, lineBreak: false });
    }
    doc.y = y + rowHeight;
  };

  drawRow(table.header.cells, true, "#f5f5f4");
  for (const row of table.rows) {
    ensureSpace(doc, rowHeight);
    drawRow(row.cells, false);
  }
}

export async function renderCompliancePdf(
  markdownContent: string,
  outputPath: string,
): Promise<string> {
  await mkdir(dirname(outputPath), { recursive: true });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 72, bottom: 72, left: 60, right: 60 },
      info: {
        Title: "KindLM EU AI Act Compliance Report",
        Author: "KindLM",
        Creator: "KindLM CLI",
      },
    });

    const stream = createWriteStream(outputPath);
    doc.pipe(stream);

    const contentWidth = (doc.page.width as number) - (doc.page.margins.left as number) - (doc.page.margins.right as number);
    const title = extractTitle(markdownContent);
    const hash = extractHash(markdownContent);

    // --- Title Page ---
    doc.moveDown(6);
    doc.fontSize(28).font("Helvetica-Bold").fillColor("#1c1917").text(title, { align: "center", width: contentWidth });
    doc.moveDown(0.5);
    doc.fontSize(14).font("Helvetica").fillColor("#57534e").text("EU AI Act Annex IV Documentation", { align: "center", width: contentWidth });
    doc.moveDown(1);
    doc.fontSize(10).fillColor("#a8a29e").text(`Generated: ${new Date().toISOString()}`, { align: "center", width: contentWidth });

    if (hash) {
      doc.moveDown(0.3);
      doc.fontSize(9).font("Courier").fillColor("#78716c").text(`SHA-256: ${hash}`, { align: "center", width: contentWidth });
    }

    doc.moveDown(2);
    doc.fontSize(10).font("Helvetica").fillColor("#6366f1").text("kindlm.com", { align: "center", link: "https://kindlm.com", width: contentWidth });

    // --- Content Pages ---
    const sections = parseSections(markdownContent);

    for (const section of sections) {
      doc.addPage();
      renderPageHeader(doc);

      if (section.heading) {
        const size = headingSize(section.headingLevel);
        doc.fontSize(size).font("Helvetica-Bold").fillColor("#1c1917").text(section.heading, { width: contentWidth });
        doc.moveDown(0.5);
        doc.moveTo(60, doc.y).lineTo(60 + contentWidth, doc.y).strokeColor("#e7e5e4").lineWidth(1).stroke();
        doc.moveDown(0.8);
      }

      const bodyLines = section.body.split("\n");
      let inCodeBlock = false;
      let i = 0;
      while (i < bodyLines.length) {
        const line = bodyLines[i] ?? "";

        if (line.startsWith("```")) {
          inCodeBlock = !inCodeBlock;
          if (inCodeBlock) {
            ensureSpace(doc, 30);
          }
          i++;
          continue;
        }

        if (inCodeBlock) {
          ensureSpace(doc, 14);
          const codeY = doc.y as number;
          doc.save();
          doc.rect(doc.page.margins.left, codeY - 2, contentWidth, 14).fill("#f5f5f4");
          doc.restore();
          doc.fontSize(9).font("Courier").fillColor("#44403c").text(line, { width: contentWidth });
          i++;
          continue;
        }

        if (!line.trim()) {
          doc.moveDown(0.4);
          i++;
          continue;
        }

        // Table detection: look ahead for separator line
        const nextLine = bodyLines[i + 1] ?? "";
        if (line.includes("|") && i + 1 < bodyLines.length && nextLine.match(/^\s*\|[-:\s|]+\|\s*$/)) {
          const tableLines: string[] = [];
          let j = i;
          while (j < bodyLines.length && (bodyLines[j] ?? "").includes("|")) {
            tableLines.push(bodyLines[j] ?? "");
            j++;
          }
          const table = parseTable(tableLines);
          if (table) {
            renderTable(doc, table, contentWidth);
            i = j;
            continue;
          }
        }

        // Skip standalone separator lines
        if (line.match(/^\s*\|[-:]+/) || line.match(/^---+$/)) {
          i++;
          continue;
        }

        // Subheadings (### and ####)
        const subheadingMatch = line.match(/^(#{3,4})\s+(.+)$/);
        if (subheadingMatch?.[1] && subheadingMatch[2]) {
          const level = subheadingMatch[1].length;
          const size = headingSize(level);
          ensureSpace(doc, size + 10);
          doc.moveDown(0.3);
          doc.fontSize(size).font("Helvetica-Bold").fillColor("#1c1917").text(subheadingMatch[2].trim(), { width: contentWidth });
          doc.moveDown(0.3);
          i++;
          continue;
        }

        // Bullet points
        if (line.match(/^\s*[-*] /)) {
          ensureSpace(doc, 14);
          doc.fontSize(10).font("Helvetica").fillColor("#44403c").text(line.trim(), { indent: 12, width: contentWidth - 12 });
          i++;
          continue;
        }

        // Regular text
        ensureSpace(doc, 14);
        doc.fontSize(10).font("Helvetica").fillColor("#44403c").text(line.trim(), { width: contentWidth });
        i++;
      }

      renderPageFooter(doc);
    }

    doc.end();

    stream.on("finish", () => resolve(outputPath));
    stream.on("error", reject);
  });
}
